"""Initial migration

Revision ID: 6fd40c1b36c7
Revises: 
Create Date: 2025-07-24 21:56:57.738233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd40c1b36c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_title', sa.String(length=80), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name='fk_list_board_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_board',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name='fk_user_board_board_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_board_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'board_id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_title', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], name='fk_card_list_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name='fk_card_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name='fk_card_user_card_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_card_user_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    op.create_table('cardactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name='fk_card_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_card_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name='fk_card_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], name='fk_checklist_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklistitem')
    op.drop_table('checklist')
    op.drop_table('cardactivity')
    op.drop_table('card_user')
    op.drop_table('attachment')
    op.drop_table('card')
    op.drop_table('user_board')
    op.drop_table('list')
    op.drop_table('user')
    op.drop_table('board')
    # ### end Alembic commands ###
